CREATE TABLE students(
	ID VARCHAR PRIMARY KEY,
	NAME VARCHAR,
	EMAIL VARCHAR
);

CREATE TABLE teachers(
	ID VARCHAR PRIMARY KEY,
	NAME VARCHAR,
	EMAIL VARCHAR
);

CREATE TABLE courses(
	ID VARCHAR PRIMARY KEY,
	NAME VARCHAR,
	TEACHER_ID VARCHAR,
	ROOM VARCHAR,
	FOREIGN KEY (TEACHER_ID) REFERENCES teachers(TEACHER_ID)
);

CREATE TABLE course_timeslots(
	COURSE_ID VARCHAR,
	DAY_OF_WEEK VARCHAR,
	TIME_PERIOD VARCHAR,
	FOREIGN KEY (COURSE_ID) REFERENCES courses(COURSE_ID)
);


CREATE TABLE student_courses(
	ID VARCHAR,
	COURSE_ID VARCHAR,
	FOREIGN KEY (ID) REFERENCES students(ID),
	FOREIGN KEY (COURSE_ID) REFERENCES courses(COURSE_ID)
);